name: Deploy to Render

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # 觸發 Render 重新部署（如配置了 webhook）
          if [ -n "$RENDER_API_KEY" ] && [ -n "$SERVICE_ID" ]; then
            curl -X POST https://api.render.com/v1/services/$SERVICE_ID/deploys \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Content-Type: application/json"
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # 停止在語法錯誤時構建
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      - name: Test imports
        run: |
          python -c "from src.environment.research import ResearchEnvironment; print('✅ Imports OK')"
